[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Stiebel"
Model = "WPF 10"
Name = "Maalämpöpumppu"
SerialNumber = "AA:AA:AA:AA:AA:AA"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Lattiaviilennys"
ConfiguredName = "Lattiaviilennys"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/cooling.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, maalämpö"
ConfiguredName = "Kesätila, maalämpö"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/summermode.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Älylämpötila"
ConfiguredName = "Älylämpötila"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/dynamic_temp.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Älylämpötila"
ConfiguredName = "Älylämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/dynamic_temp.sh"
minValue = -30


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Aulan lämpötila"
ConfiguredName = "Aulan lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh ACTUAL_TEMPERATURE_FEK"
polling = 60
minValue = -30


[[services]]
type = "TemperatureSensor"
[services.characteristics]
Name = "Ulkolämpötila"
ConfiguredName = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
#cmd = "cd stiebel; ./cmd/modbus.sh OUTSIDE_TEMPERATURE" Does not give a value, for whatever reason...
cmd = "cd stiebel; ./cmd/temp.sh"
polling = 60
minValue = -50


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "HK1 lämpötila"
ConfiguredName = "HK1 lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh ACTUAL_TEMPERATURE_HK_1"
polling = 60
minValue = -30


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "HC1 Eco lämpötila"
ConfiguredName = "HC1 Eco lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh ECO_TEMPERATURE_HC1"
polling = 60
minValue = -30


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "HC1 Comfort lämpötila"
ConfiguredName = "HC1 Comfort lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh COMFORT_TEMPERATURE_HC1"
polling = 60
minValue = -30


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Varaajan lämpötila"
ConfiguredName = "Varaajan lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh ACTUAL_BUFFER_TEMPERATURE"
polling = 60
minValue = -30


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Varaajan asetuslämpötila"
ConfiguredName = "Varaajan asetuslämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh SET_BUFFER_TEMPERATURE"
polling = 60
minValue = -30