[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Stiebel"
Model = "WPF 10"
Name = "Maalämpöpumppu"
SerialNumber = "AA:AA:AA:AA:AA:AA"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"
#polling = 60

[services.characteristics]
Name = "Lattiaviilennys"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/cooling.sh"
value = false


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, maalämpö"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/summermode.sh"
value = false

[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Aulan lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/fektemp.sh"
value = 0
minValue = -30

[[services]]
type = "TemperatureSensor"
polling = 5
[services.characteristics]
Name = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/temp.sh"
value = 0
minValue = -50