[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Stiebel"
Model = "WPF 10"
Name = "Maalämpöpumppu"
SerialNumber = "AA:AA:AA:AA:AA:AA"
FirmwareRevision = "100.1.1"


[[services]]
type = "Switch"
#polling = 60

[services.characteristics]
Name = "Lattiaviilennys"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/cooling.sh"


[[services]]
type = "Switch"

[services.characteristics]
Name = "Kesätila, maalämpö"
[services.characteristics.On]
cmd = "cd stiebel; ./cmd/summermode.sh"

[[services]]
type = "TemperatureSensor"
#polling = 60

[services.characteristics]
Name = "Aulan lämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh ACTUAL_TEMPERATURE_FEK"
minValue = -30

[[services]]
type = "TemperatureSensor"
polling = 5
[services.characteristics]
Name = "Ulkolämpötila"
[services.characteristics.CurrentTemperature]
cmd = "cd stiebel; ./cmd/modbus.sh OUTSIDE_TEMPERATURE"
minValue = -50